### PR TITLE
Controllers

### PR DESCRIPTION
**Pull request by Idhrendur**

### CODE REVIEW

**Comment by Idhrendur** [comment]
I recommend a rebase merge if you can.

**Comment by CaesarVincens** [comment]
On the Norway-Scandinavia war, I don't think there is much purpose of having it as is from Victoria, the Scandinavian army has nearly sieged down the final province of Norway, there war was done in all but the final stroke. (It might auto-finish if the victory point is controlled in HoI4)

**Comment by Idhrendur** [comment]
I agree it's mostly pointless, but I kind of like it for the sake of flavor. I can remove it in future edits if need be, though.

**Comment by CaesarVincens** [comment]
Fair enough, I certainly want to add national spirits, focuses, etc. regarding the conflict

**Pull request merged**
