### PR TITLE
Update country histories with OOBs and matching converter format.

### PR DESCRIPTION
**Pull request by Idhrendur**

### CODE REVIEW

**Comment by Idhrendur** [comment]
Actually, don't merge this yet. I'm working on making the converter output wars, and that might adjust these a little more.

**Comment by Idhrendur** [comment]
Should be good now.

**Comment by CaesarVincens** [comment]
Looks good. As a note on the SCA/NOR and the IND/TIB wars, the goals in both were nearly or completely occupied in Vic2, so I figured it'd be easier to just set them as done (Norway conquered, Tibet lost western state)

**Comment by CaesarVincens** [comment]
Also, I added a few convoys to avoid complete lack of overseas supplies for those countries as need them (everyone in the ENG/BIR war basically)

**Pull request merged**
